"""
Constantes del sistema QoriCash Trading V2
"""

# Roles de usuario
ROLE_MASTER = 'Master'
ROLE_TRADER = 'Trader'
ROLE_OPERADOR = 'Operador'

ROLES = [ROLE_MASTER, ROLE_TRADER, ROLE_OPERADOR]

# Estados de usuario
USER_STATUS_ACTIVE = 'Activo'
USER_STATUS_INACTIVE = 'Inactivo'

USER_STATUSES = [USER_STATUS_ACTIVE, USER_STATUS_INACTIVE]

# Estados de cliente
CLIENT_STATUS_ACTIVE = 'Activo'
CLIENT_STATUS_INACTIVE = 'Inactivo'

CLIENT_STATUSES = [CLIENT_STATUS_ACTIVE, CLIENT_STATUS_INACTIVE]

# Tipos de operación
OPERATION_TYPE_COMPRA = 'Compra'
OPERATION_TYPE_VENTA = 'Venta'

OPERATION_TYPES = [OPERATION_TYPE_COMPRA, OPERATION_TYPE_VENTA]

# Estados de operación
OPERATION_STATUS_PENDING = 'Pendiente'
OPERATION_STATUS_IN_PROCESS = 'En proceso'
OPERATION_STATUS_COMPLETED = 'Completada'
OPERATION_STATUS_CANCELED = 'Cancelado'

OPERATION_STATUSES = [
    OPERATION_STATUS_PENDING,
    OPERATION_STATUS_IN_PROCESS,
    OPERATION_STATUS_COMPLETED,
    OPERATION_STATUS_CANCELED
]

# Acciones de auditoría
AUDIT_CREATE_USER = 'CREATE_USER'
AUDIT_UPDATE_USER = 'UPDATE_USER'
AUDIT_DELETE_USER = 'DELETE_USER'
AUDIT_CREATE_CLIENT = 'CREATE_CLIENT'
AUDIT_UPDATE_CLIENT = 'UPDATE_CLIENT'
AUDIT_DELETE_CLIENT = 'DELETE_CLIENT'
AUDIT_CREATE_OPERATION = 'CREATE_OPERATION'
AUDIT_UPDATE_OPERATION = 'UPDATE_OPERATION'
AUDIT_CANCEL_OPERATION = 'CANCEL_OPERATION'
AUDIT_COMPLETE_OPERATION = 'COMPLETE_OPERATION'
AUDIT_LOGIN = 'LOGIN'
AUDIT_LOGOUT = 'LOGOUT'

# Límites de archivo
MAX_FILE_SIZE = 10 * 1024 * 1024  # 10 MB
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'pdf'}

# Timezone
TIMEZONE = 'America/Lima'

# Formato de fechas
DATE_FORMAT = '%Y-%m-%d'
DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'
DATETIME_FORMAT_DISPLAY = '%d/%m/%Y %H:%M'

# Paginación
DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 100
